
operator:
  enabled: true
  name: rhbk-operator
  namespace:
    enabled: true
    name: keycloak
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable-v26.0
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    enabled: true
    additionalNamespaces:
      - keycloak

keycloakSpec:
  hostname: 
    hostname: example.org
  http:
    tlsSecret: my-tls-secret
  instances: 1
