# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

name: my-operator

namespace:
  enabled: true
  name: my-operator-namespace
  annotations: {}
    # argocd.argoproj.io/sync-wave: "-75"
  labels: {}

install:
  installPlanApproval: Automatic

catalog:
  channel: stable
  source: my-operator-index
  sourceNamespace: olm

operatorGroup:
  enabled: true
  additionalNamespaces: # []
    - my-managed-namespace
  upgradeStrategy: ''
  annotations: {}
    # argocd.argoproj.io/sync-wave: "-70"
  labels: {}

subscription:
  annotations: {}
    # argocd.argoproj.io/sync-wave: "-65"
  labels: {}

config: {}
