# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

name: my-operator

namespace:
  enabled: true
  name: my-operator-namespace
  annotations: {}
  labels: {}

install:
  installPlanApproval: Automatic

catalog:
  channel: stable
  source: my-operator-index
  sourceNamespace: olm

operatorGroup:
  enabled: true
  name: my-operator
  namespace: my-operator-namespace
  additionalNamespaces: # []
    - my-managed-namespace

config: {}
