{{- if .Values.operatorGroup.enabled }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: {{ .Values.name }}-
  name: {{ printf "%s-%s" .Values.name ( randAlphaNum 8 | lower ) }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.operatorGroup.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operatorGroup.labels }}
  labels: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with .Values.operatorGroup.additionalNamespaces }}
  targetNamespaces:
    {{ toYaml . }}
{{- end }}
  upgradeStrategy: {{ default "Default" .Values.operatorGroup.upgradeStrategy }}
{{- end }}
