---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obico-base
  namespace: obico
data:
  OCTOPRINT_TUNNEL_PORT_RANGE: '0-0'
  # EMAIL_HOST: 
  # EMAIL_HOST_USER: 
  # EMAIL_HOST_PASSWORD: 
  EMAIL_PORT: '587'
  EMAIL_USE_TLS: 'True'
  DEFAULT_FROM_EMAIL: changeme@example.com
  DEBUG: 'False'    # Don't set DEBUG to True unless you know what you are doing. Otherwise the static files will be cached in browser until hard-refresh
  # ADMIN_IP_WHITELIST: 
  SITE_USES_HTTPS: 'False'
  SITE_IS_PUBLIC: 'False'
  # CSRF_TRUSTED_ORIGINS: 
  SOCIAL_LOGIN: 'False'
  REDIS_URL: redis://obico-redis-master.obico.svc:6379
  DATABASE_URL: sqlite:////app/db.sqlite3
  INTERNAL_MEDIA_HOST: http://web:3334
  ML_API_HOST: http://ml_api:3333
  ACCOUNT_ALLOW_SIGN_UP: 'False'
  WEBPACK_LOADER_ENABLED: 'False'
  # TELEGRAM_BOT_TOKEN: 
  # TWILIO_ACCOUNT_SID: 
  # TWILIO_AUTH_TOKEN: 
  # TWILIO_FROM_NUMBER: 
  # SENTRY_DSN: 
  # PUSHOVER_APP_TOKEN: 
  # SLACK_CLIENT_ID: 
  # SLACK_CLIENT_SECRET: 
  # DJANGO_SECRET_KEY: 
  # SYNDICATE:
  # VERSION:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obico-ml-api
  namespace: obico
data:
  DEBUG: 'True'
  FLASK_APP: 'server.py'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obico-web
  namespace: obico
data: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obico-tasks
  namespace: obico
data: {}
