apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obico-backend
  namespace: obico
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
