kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: obico2
  namespace: obico
spec:
  to:
    kind: Service
    name: web
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
