# Default values for external-dns-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  enable: true

  name: external-dns-operator

  namespace:
    enabled: true
    name: external-dns-operator

  install:
    installPlanApproval: Automatic

  catalog:
    channel: stable-v1
    source: redhat-operators
    sourceNamespace: openshift-marketplace

  operatorGroup:
    enabled: true
    additionalNamespaces:
      - external-dns-operator

provider:
  type: Cloudflare
  credentialData: {}
  zones: []
