apiVersion: v2
name: nvidia
description: A Helm chart for Kubernetes

type: application
version: 0.1.2
appVersion: "v25.10"

dependencies:
  - name: olm-operator
    repository: https://charts.hknlab.io
    version: 0.2.5
    alias: operator
    condition: operator.enabled
