operator:
  enabled: true
  name: trident-operator
  namespace:
    enabled: false
    name: openshift-operators
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: community-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    enabled: false
    additionalNamespaces: # []
      - openshift-operators

tridentBackendConfigs:
  - name: backend-tbc-ontap-nas
    spec: {}
