---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "0 * * * *" # Runs every hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:latest
              imagePullPolicy: Always
              tty: true # for color support
              # envFrom:
              #   - configMapRef:
              #       name: common-deployment-environment
              volumeMounts:
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
                - mountPath: /app/repos # Cache repositories
                  name: app-data
                  subPath: configarr-repos
          volumes:
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: app-data
              emptyDir: {}
              # persistentVolumeClaim:
              #   claimName: media-app-data
          restartPolicy: Never
