# Default values for nfd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  enabled: true
  name: nfd
  namespace: 
    enabled: true
    name: openshift-nfd
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    enabled: true
    additionalNamespaces: # []
      - openshift-nfd
