{{- range $clusters,$values := $.Values.managedClustersSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: {{ $values.name }}
{{- if $values.labels }}
  labels:
  {{- range $key,$value := $values.labels -}}
  {{ printf "%s: %s" $key $value | nindent 4 }}
  {{- end -}}
{{- end }}
spec:
  managedNamespaces:
    {{- $values.managedNamespaces }}
  clusterSelector:
    {{- $values.clusterSelector }}
{{- end }}
