# ---
# apiVersion: cluster.open-cluster-management.io/v1beta2
# kind: ManagedClusterSet
# metadata:
#   name: example-clusterset
# spec:
#   # used to specify a list of namespaces that will be automatically created on each member cluster
#   managedNamespaces:
#     - name: my-clusterset-ns1
#   clusterSelector:
#     selectorType: ExclusiveClusterSetLabel

# ---
# apiVersion: cluster.open-cluster-management.io/v1beta2
# kind: ManagedClusterSet
# metadata:
#   name: example-openshift-clusterset
# spec:
#   clusterSelector:
#     selectorType: LabelSelector
#     labelSelector:
#       matchLabels:
#         vendor: OpenShift
