apiVersion: v2
name: obico
description: A Helm chart for Kubernetes
type: application

version: 0.1.1

appVersion: "1.1.5"

dependencies:
  - name: valkey
    version: 3.0.2
    repository: https://charts.bitnami.com/bitnami
    alias: valkey
    condition: valkey.enabled
  - name: postgresql
    version: 16.6.3
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
