apiVersion: v2
name: obico
description: A Helm chart for Kubernetes
type: application

version: 0.1.0

appVersion: "1.1.5"

dependencies:
  - name: redis
    version: 20.12.1
    repository: https://charts.bitnami.com/bitnami
    alias: redis
    condition: redis.enabled
  - name: postgresql
    version: 16.6.3
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql
    condition: postgresql.enabled
