---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: init-bundle-sa-role
  namespace: stackrox
rules:
  - apiGroups: 
      - ""
    resources: 
      - "ecrets"
    verbs:
      - "get"
      - "create"
      - "update"
      - "patch"
