apiVersion: v2
name: openshift-servicemesh
description: A Helm chart for Kubernetes

type: application
version: 0.1.1
appVersion: "2.6.14"

dependencies:
  - name: olm-operator
    repository: https://charts.hknlab.io
    version: 0.2.5
    alias: istio
    condition: istio.enabled
  - name: olm-operator
    repository: https://charts.hknlab.io
    version: 0.2.5
    alias: kiali
    condition: kiali.enabled
  - name: olm-operator
    repository: https://charts.hknlab.io
    version: 0.2.5
    alias: jaeger
    condition: jaeger.enabled
