# Default values for openshift-servicemesh-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kiali:
  name: kiali-ossm
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace

istio:
  name: servicemeshoperator
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace

jaeger:
  enabled: false
  name: jaeger-product
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    additionalNamespaces: # []
      - openshift-distributed-tracing
