{{- $namespace := $.Release.Namespace -}}
{{- range $pool := $.Values.nodePool -}}
{{- $_ := set $pool "releaseImage" $.Values.release.image -}}
{{- $_ := set $pool "clusterName" $.Values.cluster.name -}}
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- include "hosted-control-planes.node-pool.spec" . | nindent 2 }}
{{- end -}}
