apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    feature-defaults.platform.stackrox.io/admissionControllerEnforcement: Enabled
    feature-defaults.platform.stackrox.io/scannerV4: AutoSense
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: {{ .Values.clusterName }}
  centralEndpoint: {{ .Values.centralEndpoint }}
