---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env" .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  TZ: Etc/UTC
  PUID: '1000'
  PGID: '1000'
  DISABLE_BUILTIN_AUTH: 'false'
