
operator:
  enabled: true
  name: rhacs-operator
  namespace:
    enabled: true
    name: rhacs-operator
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    enabled: true
    additionalNamespaces: []
