# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  enable: true
  name: openshift-cert-manager-operator
  install:
    installPlanApproval: Automatic
  catalog:
    channel: stable-v1
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  operatorGroup:
    enable: true
    namespace: cert-manager-operator
    additionalNamespaces: {}
    # - cert-manager

issuer:
  cluster: true
  acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
  email: ""
  preferredChain: ""
  privateKeySecretRef: ""
  solvers: []
