# Default values for openshift-configuration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeport:
  enabled: false
  start: 30000
  end: 32767

banner:
  enabled: true
  location: ''
  text: ''
  color: ''
  backgroundColor: ''

oauth:
  enabled: false
  name: ''
  url: ''
  bindDN: ''
  externalSecretName: ''
