apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    olm.managed: "true"
    operators.coreos.com/cluster-logging.openshift-logging: ""
  name: logging-collector
  namespace: openshift-logging
