name: Helm Release OCI

on:
  workflow_dispatch: {}
  workflow_call: {}
  # workflow_run:
  #   workflows:
  #     - Release Helm Charts
  #   types:
  #     - completed
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   paths:
  #     - 'charts/**'

jobs:
  release-oci:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    runs-on: ubuntu-latest
    permissions:
      packages: write # needed to write OCI Releases

    steps:
      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
          done
