name: Lint Helm Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up Helm
      #   uses: azure/setup-helm@v4
      #   with:
      #     version: v3.14.0
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Add Helm Repos
        run: |
          helm repo add hknlab https://charts.hknlab.io

      - name: List charts
        run: |
          for chart in charts/*/; do
            echo "Linting $chart"
            helm lint "$chart"
          done

      - name: Run chart-testing lint
        uses: helm/chart-testing-action@v2.8.0

      # - name: Run ct lint
      #   run: ct lint --config ct.yaml
